baseURL = 'http://example.org/'
languageCode = 'ja-jp'
title = 'Kais-Docs'
publishDir = "docs"
canonifyurls = true
# https://qiita.com/ysdyt/items/a581277dd1312a0e83c3#github-pages%E3%81%A7%E5%85%AC%E9%96%8B%E3%81%99%E3%82%8B

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false